---
- name: install haproxy and socat
  package:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - haproxy
    - socat

- name: deploy haproxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Ensure HAProxy is started and enabled on boot.
  service:
    name: haproxy
    state: started
    enabled: yes
